window.I18N = {
    'zh-CN': { extName: 'PlainTab · 极简起始页', searchPlaceholder: '在 Web 中搜索…', engineTitle: '点击切换搜索引擎 | 回车搜索', langTitle: '切换语言', settingsTitle: '壁纸设置', panelTitle: '🖼️ Wallpaper', wpBing: '🌄 Bing 每日壁纸', wpLocal: '📷 本地壁纸', uploadBtn: '📁 选择本地壁纸', resetBtn: '🔄 恢复 Bing 每日壁纸', advToggle: '⚙️ 高级选项', searchLabel: '搜索栏模式', searchHover: '鼠标触发', searchAlways: '常驻显示', searchNever: '始终隐藏', opacityLabel: '图标不透明度', engineLabel: '搜索引擎', resetAdv: '🔄 恢复高级默认', fileError: '请选择图片文件', bingError: 'Bing 图片源失效', langPanelTitle: '🌐 Language' },
    'zh-TW': { extName: 'PlainTab · 極簡起始頁', searchPlaceholder: '在 Web 中搜尋…', engineTitle: '點擊切換搜尋引擎 | Enter 搜尋', langTitle: '切換語言', settingsTitle: '桌布設定', panelTitle: '🖼️ Wallpaper', wpBing: '🌄 Bing 每日桌布', wpLocal: '📷 本機圖片', uploadBtn: '📁 選擇本機桌布', resetBtn: '🔄 回復為 Bing 每日桌布', advToggle: '⚙️ 進階選項', searchLabel: '搜尋列模式', searchHover: '滑鼠觸發', searchAlways: '常駐顯示', searchNever: '始終隱藏', opacityLabel: '圖示不透明度', engineLabel: '搜尋引擎', resetAdv: '🔄 回復進階預設值', fileError: '請選擇圖片檔案', bingError: 'Bing 圖片來源失效', langPanelTitle: '🌐 Language' },
    'en': { extName: 'PlainTab · Minimal Start Page', searchPlaceholder: 'Search the Web…', engineTitle: 'Click to switch engine | Enter to search', langTitle: 'Switch Language', settingsTitle: 'Wallpaper Settings', panelTitle: '🖼️ Wallpaper', wpBing: '🌄 Bing daily', wpLocal: '📷 Local image', uploadBtn: '📁 Choose local wallpaper', resetBtn: '🔄 Reset to Bing daily', advToggle: '⚙️ Advanced', searchLabel: 'Search bar mode', searchHover: 'On hover', searchAlways: 'Always', searchNever: 'Hidden', opacityLabel: 'Icon opacity', engineLabel: 'Search engine', resetAdv: '🔄 Reset advanced defaults', fileError: 'Please select an image file', bingError: 'Bing image source unavailable', langPanelTitle: '🌐 Language', addImage: 'Add wallpaper', deleteImage: 'Remove', imageCount: 'images', imageLimit: 'Up to 12 wallpapers', resetConfirm: 'This will remove all local wallpapers. Continue?' },
    'es': { extName: 'PlainTab · Página Minimalista', searchPlaceholder: 'Buscar en la Web…', engineTitle: 'Clic para cambiar motor | Enter para buscar', langTitle: 'Cambiar idioma', settingsTitle: 'Configuración del fondo', panelTitle: '🖼️ Wallpaper', wpBing: '🌄 Bing diario', wpLocal: '📷 Imagen local', uploadBtn: '📁 Elegir fondo local', resetBtn: '🔄 Restablecer a Bing diario', advToggle: '⚙️ Avanzado', searchLabel: 'Modo de búsqueda', searchHover: 'Al pasar', searchAlways: 'Siempre', searchNever: 'Nunca', opacityLabel: 'Opacidad del icono', engineLabel: 'Motor de búsqueda', resetAdv: '🔄 Restablecer ajustes avanzados', fileError: 'Selecciona un archivo de imagen', bingError: 'Fuente Bing no disponible', langPanelTitle: '🌐 Language' },
    'hi': { extName: 'PlainTab · न्यूनतम प्रारंभ पृष्ठ', searchPlaceholder: 'वेब पर खोजें…', engineTitle: 'इंजन बदलने के लिए क्लिक करें | खोजने के लिए Enter', langTitle: 'भाषा बदलें', settingsTitle: 'वॉलपेपर सेटिंग', panelTitle: '🖼️ Wallpaper', wpBing: '🌄 Bing दैनिक', wpLocal: '📷 स्थानीय चित्र', uploadBtn: '📁 स्थानीय वॉलपेपर चुनें', resetBtn: '🔄 Bing दैनिक पर रीसेट करें', advToggle: '⚙️ उन्नत', searchLabel: 'खोज बार मोड', searchHover: 'होवर पर', searchAlways: 'हमेशा', searchNever: 'कभी नहीं', opacityLabel: 'आइकन अपारदर्शिता', engineLabel: 'खोज इंजन', resetAdv: '🔄 उन्नत डिफ़ॉल्ट रीसेट करें', fileError: 'कृपया एक छवि फ़ाइल चुनें', bingError: 'Bing चित्र स्रोत अनुपलब्ध', langPanelTitle: '🌐 Language' },
    'ar': { extName: 'PlainTab · صفحة بداية بسيطة', searchPlaceholder: 'ابحث في الويب…', engineTitle: 'انقر لتبديل المحرك | Enter للبحث', langTitle: 'تغيير اللغة', settingsTitle: 'إعدادات الخلفية', panelTitle: '🖼️ Wallpaper', wpBing: '🌄 Bing اليومي', wpLocal: '📷 صورة محلية', uploadBtn: '📁 اختر خلفية محلية', resetBtn: '🔄 إعادة تعيين إلى Bing اليومي', advToggle: '⚙️ متقدم', searchLabel: 'وضع شريط البحث', searchHover: 'عند التمرير', searchAlways: 'دائمًا', searchNever: 'أبدًا', opacityLabel: 'شفافية الأيقونة', engineLabel: 'محرك البحث', resetAdv: '🔄 إعادة تعيين الإعدادات', fileError: 'يرجى اختيار ملف صورة', bingError: 'مصدر صورة Bing غير متاح', langPanelTitle: '🌐 Language' },
    'pt': { extName: 'PlainTab · Página Inicial Minimalista', searchPlaceholder: 'Pesquisar na Web…', engineTitle: 'Clique para trocar | Enter para buscar', langTitle: 'Alterar idioma', settingsTitle: 'Configurações do papel de parede', panelTitle: '🖼️ Wallpaper', wpBing: '🌄 Bing diário', wpLocal: '📷 Imagem local', uploadBtn: '📁 Escolher papel de parede local', resetBtn: '🔄 Redefinir para Bing diário', advToggle: '⚙️ Avançado', searchLabel: 'Modo da barra de pesquisa', searchHover: 'Ao passar', searchAlways: 'Sempre', searchNever: 'Nunca', opacityLabel: 'Opacidade do ícone', engineLabel: 'Mecanismo de pesquisa', resetAdv: '🔄 Redefinir padrões avançados', fileError: 'Selecione um arquivo de imagem', bingError: 'Fonte de imagem Bing indisponível', langPanelTitle: '🌐 Language' },
    'ru': { extName: 'PlainTab · Минималистичная стартовая страница', searchPlaceholder: 'Поиск в Интернете…', engineTitle: 'Нажмите для смены поисковика | Enter для поиска', langTitle: 'Сменить язык', settingsTitle: 'Настройки обоев', panelTitle: '🖼️ Wallpaper', wpBing: '🌄 Bing дня', wpLocal: '📷 Локальное изображение', uploadBtn: '📁 Выбрать локальные обои', resetBtn: '🔄 Сбросить на Bing дня', advToggle: '⚙️ Дополнительно', searchLabel: 'Режим строки поиска', searchHover: 'При наведении', searchAlways: 'Всегда', searchNever: 'Никогда', opacityLabel: 'Прозрачность значка', engineLabel: 'Поисковая система', resetAdv: '🔄 Сбросить доп. настройки', fileError: 'Выберите файл изображения', bingError: 'Источник Bing недоступен', langPanelTitle: '🌐 Language' },
    'ja': { extName: 'PlainTab · ミニマルなスタートページ', searchPlaceholder: 'Web を検索…', engineTitle: '検索エンジン切替 | Enter で検索', langTitle: '言語切替', settingsTitle: '壁紙設定', panelTitle: '🖼️ Wallpaper', wpBing: '🌄 Bing 毎日壁紙', wpLocal: '📷 ローカル壁紙', uploadBtn: '📁 ローカル壁紙を選択', resetBtn: '🔄 Bing 毎日壁紙に戻す', advToggle: '⚙️ 詳細設定', searchLabel: '検索バー表示', searchHover: 'ホバー時', searchAlways: '常に表示', searchNever: '非表示', opacityLabel: 'アイコン不透明度', engineLabel: '検索エンジン', resetAdv: '🔄 詳細設定をリセット', fileError: '画像ファイルを選択してください', bingError: 'Bing画像ソース利用不可', langPanelTitle: '🌐 Language' },
    'de': { extName: 'PlainTab · Minimalistische Startseite', searchPlaceholder: 'Im Web suchen…', engineTitle: 'Klick zum Wechseln | Enter zum Suchen', langTitle: 'Sprache wechseln', settingsTitle: 'Hintergrundeinstellungen', panelTitle: '🖼️ Wallpaper', wpBing: '🌄 Bing Tägliches Bild', wpLocal: '📷 Lokales Bild', uploadBtn: '📁 Lokales Hintergrundbild wählen', resetBtn: '🔄 Auf Bing Tägliches Bild zurücksetzen', advToggle: '⚙️ Erweitert', searchLabel: 'Suchleistenmodus', searchHover: 'Beim Überfahren', searchAlways: 'Immer', searchNever: 'Nie', opacityLabel: 'Symbol-Transparenz', engineLabel: 'Suchmaschine', resetAdv: '🔄 Erweiterte Einstellungen zurücksetzen', fileError: 'Bitte wählen Sie eine Bilddatei', bingError: 'Bing-Bildquelle nicht verfügbar', langPanelTitle: '🌐 Language' },
    'ko': { extName: 'PlainTab · 미니멀 스타트 페이지', searchPlaceholder: '웹 검색…', engineTitle: '검색 엔진 전환 | Enter로 검색', langTitle: '언어 전환', settingsTitle: '배경화면 설정', panelTitle: '🖼️ Wallpaper', wpBing: '🌄 Bing 매일 배경', wpLocal: '📷 로컬 이미지', uploadBtn: '📁 로컬 배경 선택', resetBtn: '🔄 Bing 매일 배경으로 복원', advToggle: '⚙️ 고급 설정', searchLabel: '검색창 표시', searchHover: '호버 시', searchAlways: '항상 표시', searchNever: '숨기기', opacityLabel: '아이콘 불투명도', engineLabel: '검색 엔진', resetAdv: '🔄 고급 설정 초기화', fileError: '이미지 파일을 선택하세요', bingError: 'Bing 이미지 소스 사용 불가', langPanelTitle: '🌐 Language' },
    'fr': { extName: 'PlainTab · Page de démarrage minimaliste', searchPlaceholder: 'Rechercher sur le Web…', engineTitle: 'Cliquez pour changer | Entrée pour rechercher', langTitle: 'Changer de langue', settingsTitle: 'Paramètres du fond d\'écran', panelTitle: '🖼️ Wallpaper', wpBing: '🌄 Bing du jour', wpLocal: '📷 Image locale', uploadBtn: '📁 Choisir un fond d\'écran local', resetBtn: '🔄 Réinitialiser à Bing du jour', advToggle: '⚙️ Avancé', searchLabel: 'Mode de la barre de recherche', searchHover: 'Au survol', searchAlways: 'Toujours', searchNever: 'Jamais', opacityLabel: 'Opacité de l\'icône', engineLabel: 'Moteur de recherche', resetAdv: '🔄 Réinitialiser les paramètres', fileError: 'Sélectionnez un fichier image', bingError: 'Source d\'image Bing indisponible', langPanelTitle: '🌐 Language' },
    'it': { extName: 'PlainTab · Pagina iniziale minimalista', searchPlaceholder: 'Cerca nel Web…', engineTitle: 'Clicca per cambiare | Invio per cercare', langTitle: 'Cambia lingua', settingsTitle: 'Impostazioni sfondo', panelTitle: '🖼️ Wallpaper', wpBing: '🌄 Bing giornaliero', wpLocal: '📷 Immagine locale', uploadBtn: '📁 Scegli sfondo locale', resetBtn: '🔄 Ripristina a Bing giornaliero', advToggle: '⚙️ Avanzate', searchLabel: 'Modalità barra di ricerca', searchHover: 'Al passaggio', searchAlways: 'Sempre', searchNever: 'Mai', opacityLabel: 'Opacità icona', engineLabel: 'Motore di ricerca', resetAdv: '🔄 Ripristina impostazioni', fileError: 'Seleziona un file immagine', bingError: 'Sorgente immagine Bing non disponibile', langPanelTitle: '🌐 Language' },
    'tr': { extName: 'PlainTab · Minimal Başlangıç Sayfası', searchPlaceholder: 'Web\'de ara…', engineTitle: 'Motoru değiştirmek için tıkla | Aramak için Enter', langTitle: 'Dil değiştir', settingsTitle: 'Duvar kağıdı ayarları', panelTitle: '🖼️ Wallpaper', wpBing: '🌄 Bing günlük', wpLocal: '📷 Yerel resim', uploadBtn: '📁 Yerel duvar kağıdı seç', resetBtn: '🔄 Bing günlük olarak sıfırla', advToggle: '⚙️ Gelişmiş', searchLabel: 'Arama çubuğu modu', searchHover: 'Üzerine gelince', searchAlways: 'Her zaman', searchNever: 'Asla', opacityLabel: 'Simge opaklığı', engineLabel: 'Arama motoru', resetAdv: '🔄 Gelişmiş ayarları sıfırla', fileError: 'Lütfen bir resim dosyası seçin', bingError: 'Bing resim kaynağı kullanılamıyor', langPanelTitle: '🌐 Language' },
    'pl': { extName: 'PlainTab · Minimalistyczna strona startowa', searchPlaceholder: 'Szukaj w internecie…', engineTitle: 'Kliknij, aby zmienić | Enter, aby szukać', langTitle: 'Zmień język', settingsTitle: 'Ustawienia tapety', panelTitle: '🖼️ Wallpaper', wpBing: '🌄 Bing dnia', wpLocal: '📷 Obraz lokalny', uploadBtn: '📁 Wybierz lokalną tapetę', resetBtn: '🔄 Przywróć Bing dnia', advToggle: '⚙️ Zaawansowane', searchLabel: 'Tryb paska wyszukiwania', searchHover: 'Po najechaniu', searchAlways: 'Zawsze', searchNever: 'Nigdy', opacityLabel: 'Przezroczystość ikony', engineLabel: 'Silnik wyszukiwania', resetAdv: '🔄 Przywróć zaawansowane', fileError: 'Wybierz plik obrazu', bingError: 'Źródło obrazów Bing niedostępne', langPanelTitle: '🌐 Language' },
    'vi': { extName: 'PlainTab · Trang bắt đầu tối giản', searchPlaceholder: 'Tìm kiếm trên Web…', engineTitle: 'Nhấp để đổi công cụ | Enter để tìm', langTitle: 'Đổi ngôn ngữ', settingsTitle: 'Cài đặt hình nền', panelTitle: '🖼️ Wallpaper', wpBing: '🌄 Bing hàng ngày', wpLocal: '📷 Ảnh cục bộ', uploadBtn: '📁 Chọn hình nền cục bộ', resetBtn: '🔄 Đặt lại về Bing hàng ngày', advToggle: '⚙️ Nâng cao', searchLabel: 'Chế độ thanh tìm kiếm', searchHover: 'Khi di chuột', searchAlways: 'Luôn hiện', searchNever: 'Ẩn', opacityLabel: 'Độ mờ biểu tượng', engineLabel: 'Công cụ tìm kiếm', resetAdv: '🔄 Đặt lại cài đặt nâng cao', fileError: 'Vui lòng chọn tệp hình ảnh', bingError: 'Nguồn ảnh Bing không khả dụng', langPanelTitle: '🌐 Language' }
};

window.LanguageList = [
    { code: 'zh-CN', name: '中文 (简体)' },
    { code: 'zh-TW', name: '中文 (繁體)' },
    { code: 'en', name: 'English' },
    { code: 'es', name: 'Español' },
    { code: 'hi', name: 'हिन्दी' },
    { code: 'ar', name: 'العربية' },
    { code: 'pt', name: 'Português' },
    { code: 'ru', name: 'Русский' },
    { code: 'ja', name: '日本語' },
    { code: 'de', name: 'Deutsch' },
    { code: 'ko', name: '한국어' },
    { code: 'fr', name: 'Français' },
    { code: 'it', name: 'Italiano' },
    { code: 'tr', name: 'Türkçe' },
    { code: 'pl', name: 'Polski' },
    { code: 'vi', name: 'Tiếng Việt' }
];
