// ===================== 多语言包 (16种语言) =====================
window.I18N = {
    'zh-CN': {
        extName: 'PlainTab · 极简起始页',
        search_placeholder: '在 Web 中搜索…',
        search_engine_title: '点击切换搜索引擎 | 回车搜索',
        lang_button_title: '切换语言',
        settings_icon_title: '壁纸设置',
        panel_title: '🖼️ 壁纸设置',
        wallpaper_bing: '当前：🌄 Bing 每日壁纸',
        wallpaper_local: '当前：📷 本地壁纸',
        upload_btn: '📁 选择本地壁纸',
        reset_btn: '🔄 恢复 Bing 每日壁纸',
        advanced_toggle: '⚙️ 高级选项',
        search_mode_label: '搜索栏模式',
        search_mode_hover: '鼠标触发',
        search_mode_always: '常驻显示',
        search_mode_never: '始终隐藏',
        icon_opacity_label: '齿轮不透明度',
        search_engine_label: '搜索引擎',
        reset_advanced_btn: '🔄 恢复高级默认',
        local_upload_error: '壁纸保存失败: ',
        file_type_error: '请选择图片文件',
        bing_source_error: 'Bing图片源失效',
        language_panel_title: '🌐 语言'
    },
    'zh-TW': {
        extName: 'PlainTab · 極簡起始頁',
        search_placeholder: '在 Web 中搜尋…',
        search_engine_title: '點擊切換搜尋引擎 | 按 Enter 搜尋',
        lang_button_title: '切換語言',
        settings_icon_title: '桌布設定',
        panel_title: '🖼️ 桌布設定',
        wallpaper_bing: '目前：🌄 Bing 每日桌布',
        wallpaper_local: '目前：📷 本機圖片',
        upload_btn: '📁 選擇本機桌布',
        reset_btn: '🔄 回復為 Bing 每日桌布',
        advanced_toggle: '⚙️ 進階選項',
        search_mode_label: '搜尋列模式',
        search_mode_hover: '滑鼠觸發',
        search_mode_always: '常駐顯示',
        search_mode_never: '始終隱藏',
        icon_opacity_label: '齒輪不透明度',
        search_engine_label: '搜尋引擎',
        reset_advanced_btn: '🔄 回復進階預設值',
        local_upload_error: '桌布儲存失敗: ',
        file_type_error: '請選擇圖片檔案',
        bing_source_error: 'Bing 圖片來源失效',
        language_panel_title: '🌐 語言'
    },
    'en': {
        extName: 'PlainTab · Minimal Start Page',
        search_placeholder: 'Search the Web…',
        search_engine_title: 'Click to switch engine | Enter to search',
        lang_button_title: 'Switch Language',
        settings_icon_title: 'Wallpaper Settings',
        panel_title: '🖼️ Wallpaper Settings',
        wallpaper_bing: 'Current: 🌄 Bing daily',
        wallpaper_local: 'Current: 📷 Local image',
        upload_btn: '📁 Choose local wallpaper',
        reset_btn: '🔄 Reset to Bing daily',
        advanced_toggle: '⚙️ Advanced',
        search_mode_label: 'Search bar mode',
        search_mode_hover: 'Hover',
        search_mode_always: 'Always',
        search_mode_never: 'Never',
        icon_opacity_label: 'Icon opacity',
        search_engine_label: 'Search engine',
        reset_advanced_btn: '🔄 Reset advanced defaults',
        local_upload_error: 'Wallpaper save failed: ',
        file_type_error: 'Please select an image file',
        bing_source_error: 'Bing image source unavailable',
        language_panel_title: '🌐 Language'
    },
    'es': {
        extName: 'PlainTab · Página de Inicio Minimalista',
        search_placeholder: 'Buscar en la Web…',
        search_engine_title: 'Clic para cambiar motor | Enter para buscar',
        lang_button_title: 'Cambiar idioma',
        settings_icon_title: 'Configuración del fondo',
        panel_title: '🖼️ Configuración del fondo',
        wallpaper_bing: 'Actual: 🌄 Bing diario',
        wallpaper_local: 'Actual: 📷 Imagen local',
        upload_btn: '📁 Elegir fondo local',
        reset_btn: '🔄 Restablecer a Bing diario',
        advanced_toggle: '⚙️ Avanzado',
        search_mode_label: 'Modo de barra de búsqueda',
        search_mode_hover: 'Al pasar',
        search_mode_always: 'Siempre',
        search_mode_never: 'Nunca',
        icon_opacity_label: 'Opacidad del icono',
        search_engine_label: 'Motor de búsqueda',
        reset_advanced_btn: '🔄 Restablecer ajustes avanzados',
        local_upload_error: 'Error al guardar la imagen: ',
        file_type_error: 'Selecciona un archivo de imagen',
        bing_source_error: 'Fuente de imagen Bing no disponible',
        language_panel_title: '🌐 Idioma'
    },
    'hi': {
        extName: 'PlainTab · न्यूनतम प्रारंभ पृष्ठ',
        search_placeholder: 'वेब पर खोजें…',
        search_engine_title: 'इंजन बदलने के लिए क्लिक करें | खोजने के लिए Enter दबाएं',
        lang_button_title: 'भाषा बदलें',
        settings_icon_title: 'वॉलपेपर सेटिंग',
        panel_title: '🖼️ वॉलपेपर सेटिंग',
        wallpaper_bing: 'वर्तमान: 🌄 Bing दैनिक',
        wallpaper_local: 'वर्तमान: 📷 स्थानीय चित्र',
        upload_btn: '📁 स्थानीय वॉलपेपर चुनें',
        reset_btn: '🔄 Bing दैनिक पर रीसेट करें',
        advanced_toggle: '⚙️ उन्नत',
        search_mode_label: 'खोज बार मोड',
        search_mode_hover: 'होवर पर',
        search_mode_always: 'हमेशा',
        search_mode_never: 'कभी नहीं',
        icon_opacity_label: 'आइकन अपारदर्शिता',
        search_engine_label: 'खोज इंजन',
        reset_advanced_btn: '🔄 उन्नत डिफ़ॉल्ट रीसेट करें',
        local_upload_error: 'वॉलपेपर सहेजने में विफल: ',
        file_type_error: 'कृपया एक छवि फ़ाइल चुनें',
        bing_source_error: 'Bing चित्र स्रोत अनुपलब्ध',
        language_panel_title: '🌐 भाषा'
    },
    'ar': {
        extName: 'PlainTab · صفحة بداية بسيطة',
        search_placeholder: 'ابحث في الويب…',
        search_engine_title: 'انقر لتبديل المحرك | Enter للبحث',
        lang_button_title: 'تغيير اللغة',
        settings_icon_title: 'إعدادات الخلفية',
        panel_title: '🖼️ إعدادات الخلفية',
        wallpaper_bing: 'الحالي: 🌄 Bing اليومي',
        wallpaper_local: 'الحالي: 📷 صورة محلية',
        upload_btn: '📁 اختر خلفية محلية',
        reset_btn: '🔄 إعادة تعيين إلى Bing اليومي',
        advanced_toggle: '⚙️ متقدم',
        search_mode_label: 'وضع شريط البحث',
        search_mode_hover: 'عند التمرير',
        search_mode_always: 'دائمًا',
        search_mode_never: 'أبدًا',
        icon_opacity_label: 'شفافية الأيقونة',
        search_engine_label: 'محرك البحث',
        reset_advanced_btn: '🔄 إعادة تعيين الإعدادات المتقدمة',
        local_upload_error: 'فشل حفظ الخلفية: ',
        file_type_error: 'يرجى اختيار ملف صورة',
        bing_source_error: 'مصدر صورة Bing غير متاح',
        language_panel_title: '🌐 اللغة'
    },
    'pt': {
        extName: 'PlainTab · Página Inicial Minimalista',
        search_placeholder: 'Pesquisar na Web…',
        search_engine_title: 'Clique para trocar mecanismo | Enter para buscar',
        lang_button_title: 'Alterar idioma',
        settings_icon_title: 'Configurações do papel de parede',
        panel_title: '🖼️ Configurações do papel de parede',
        wallpaper_bing: 'Atual: 🌄 Bing diário',
        wallpaper_local: 'Atual: 📷 Imagem local',
        upload_btn: '📁 Escolher papel de parede local',
        reset_btn: '🔄 Redefinir para Bing diário',
        advanced_toggle: '⚙️ Avançado',
        search_mode_label: 'Modo da barra de pesquisa',
        search_mode_hover: 'Ao passar',
        search_mode_always: 'Sempre',
        search_mode_never: 'Nunca',
        icon_opacity_label: 'Opacidade do ícone',
        search_engine_label: 'Mecanismo de pesquisa',
        reset_advanced_btn: '🔄 Redefinir padrões avançados',
        local_upload_error: 'Falha ao salvar papel de parede: ',
        file_type_error: 'Selecione um arquivo de imagem',
        bing_source_error: 'Fonte de imagem do Bing indisponível',
        language_panel_title: '🌐 Idioma'
    },
    'ru': {
        extName: 'PlainTab · Минималистичная стартовая страница',
        search_placeholder: 'Поиск в Интернете…',
        search_engine_title: 'Нажмите для смены поисковика | Enter для поиска',
        lang_button_title: 'Сменить язык',
        settings_icon_title: 'Настройки обоев',
        panel_title: '🖼️ Настройки обоев',
        wallpaper_bing: 'Сейчас: 🌄 Bing дня',
        wallpaper_local: 'Сейчас: 📷 Локальное изображение',
        upload_btn: '📁 Выбрать локальные обои',
        reset_btn: '🔄 Сбросить на Bing дня',
        advanced_toggle: '⚙️ Дополнительно',
        search_mode_label: 'Режим строки поиска',
        search_mode_hover: 'При наведении',
        search_mode_always: 'Всегда',
        search_mode_never: 'Никогда',
        icon_opacity_label: 'Прозрачность значка',
        search_engine_label: 'Поисковая система',
        reset_advanced_btn: '🔄 Сбросить доп. настройки',
        local_upload_error: 'Ошибка сохранения обоев: ',
        file_type_error: 'Пожалуйста, выберите файл изображения',
        bing_source_error: 'Источник изображений Bing недоступен',
        language_panel_title: '🌐 Язык'
    },
    'ja': {
        extName: 'PlainTab · ミニマルなスタートページ',
        search_placeholder: 'Web を検索…',
        search_engine_title: '検索エンジン切替 | Enter で検索',
        lang_button_title: '言語切替',
        settings_icon_title: '壁紙設定',
        panel_title: '🖼️ 壁紙設定',
        wallpaper_bing: '現在：🌄 Bing 毎日壁紙',
        wallpaper_local: '現在：📷 ローカル壁紙',
        upload_btn: '📁 ローカル壁紙を選択',
        reset_btn: '🔄 Bing 毎日壁紙に戻す',
        advanced_toggle: '⚙️ 詳細設定',
        search_mode_label: '検索バー表示',
        search_mode_hover: 'ホバー時',
        search_mode_always: '常に表示',
        search_mode_never: '非表示',
        icon_opacity_label: 'アイコン不透明度',
        search_engine_label: '検索エンジン',
        reset_advanced_btn: '🔄 詳細設定をリセット',
        local_upload_error: '壁紙の保存に失敗: ',
        file_type_error: '画像ファイルを選択してください',
        bing_source_error: 'Bing画像ソース利用不可',
        language_panel_title: '🌐 言語'
    },
    'de': {
        extName: 'PlainTab · Minimalistische Startseite',
        search_placeholder: 'Im Web suchen…',
        search_engine_title: 'Klick zum Wechseln der Suchmaschine | Enter zum Suchen',
        lang_button_title: 'Sprache wechseln',
        settings_icon_title: 'Hintergrundeinstellungen',
        panel_title: '🖼️ Hintergrundeinstellungen',
        wallpaper_bing: 'Aktuell: 🌄 Bing Tägliches Bild',
        wallpaper_local: 'Aktuell: 📷 Lokales Bild',
        upload_btn: '📁 Lokales Hintergrundbild wählen',
        reset_btn: '🔄 Auf Bing Tägliches Bild zurücksetzen',
        advanced_toggle: '⚙️ Erweitert',
        search_mode_label: 'Suchleistenmodus',
        search_mode_hover: 'Beim Überfahren',
        search_mode_always: 'Immer',
        search_mode_never: 'Nie',
        icon_opacity_label: 'Symbol-Transparenz',
        search_engine_label: 'Suchmaschine',
        reset_advanced_btn: '🔄 Erweiterte Einstellungen zurücksetzen',
        local_upload_error: 'Hintergrund konnte nicht gespeichert werden: ',
        file_type_error: 'Bitte wählen Sie eine Bilddatei aus',
        bing_source_error: 'Bing-Bildquelle nicht verfügbar',
        language_panel_title: '🌐 Sprache'
    },
    'ko': {
        extName: 'PlainTab · 미니멀 스타트 페이지',
        search_placeholder: '웹 검색…',
        search_engine_title: '검색 엔진 전환 | Enter로 검색',
        lang_button_title: '언어 전환',
        settings_icon_title: '배경화면 설정',
        panel_title: '🖼️ 배경화면 설정',
        wallpaper_bing: '현재: 🌄 Bing 매일 배경',
        wallpaper_local: '현재: 📷 로컬 이미지',
        upload_btn: '📁 로컬 배경 선택',
        reset_btn: '🔄 Bing 매일 배경으로 복원',
        advanced_toggle: '⚙️ 고급 설정',
        search_mode_label: '검색창 표시',
        search_mode_hover: '호버 시',
        search_mode_always: '항상 표시',
        search_mode_never: '숨기기',
        icon_opacity_label: '아이콘 불투명도',
        search_engine_label: '검색 엔진',
        reset_advanced_btn: '🔄 고급 설정 초기화',
        local_upload_error: '배경 저장 실패: ',
        file_type_error: '이미지 파일을 선택하세요',
        bing_source_error: 'Bing 이미지 소스 사용 불가',
        language_panel_title: '🌐 언어'
    },
    'fr': {
        extName: 'PlainTab · Page de démarrage minimaliste',
        search_placeholder: 'Rechercher sur le Web…',
        search_engine_title: 'Cliquez pour changer de moteur | Entrée pour rechercher',
        lang_button_title: 'Changer de langue',
        settings_icon_title: 'Paramètres du fond d\'écran',
        panel_title: '🖼️ Paramètres du fond d\'écran',
        wallpaper_bing: 'Actuel : 🌄 Bing du jour',
        wallpaper_local: 'Actuel : 📷 Image locale',
        upload_btn: '📁 Choisir un fond d\'écran local',
        reset_btn: '🔄 Réinitialiser à Bing du jour',
        advanced_toggle: '⚙️ Avancé',
        search_mode_label: 'Mode de la barre de recherche',
        search_mode_hover: 'Au survol',
        search_mode_always: 'Toujours',
        search_mode_never: 'Jamais',
        icon_opacity_label: 'Opacité de l\'icône',
        search_engine_label: 'Moteur de recherche',
        reset_advanced_btn: '🔄 Réinitialiser les paramètres avancés',
        local_upload_error: 'Échec de l\'enregistrement du fond d\'écran : ',
        file_type_error: 'Veuillez sélectionner un fichier image',
        bing_source_error: 'Source d\'image Bing indisponible',
        language_panel_title: '🌐 Langue'
    },
    'it': {
        extName: 'PlainTab · Pagina iniziale minimalista',
        search_placeholder: 'Cerca nel Web…',
        search_engine_title: 'Clicca per cambiare motore | Invio per cercare',
        lang_button_title: 'Cambia lingua',
        settings_icon_title: 'Impostazioni sfondo',
        panel_title: '🖼️ Impostazioni sfondo',
        wallpaper_bing: 'Attuale: 🌄 Bing giornaliero',
        wallpaper_local: 'Attuale: 📷 Immagine locale',
        upload_btn: '📁 Scegli sfondo locale',
        reset_btn: '🔄 Ripristina a Bing giornaliero',
        advanced_toggle: '⚙️ Avanzate',
        search_mode_label: 'Modalità barra di ricerca',
        search_mode_hover: 'Al passaggio',
        search_mode_always: 'Sempre',
        search_mode_never: 'Mai',
        icon_opacity_label: 'Opacità icona',
        search_engine_label: 'Motore di ricerca',
        reset_advanced_btn: '🔄 Ripristina impostazioni avanzate',
        local_upload_error: 'Salvataggio sfondo fallito: ',
        file_type_error: 'Seleziona un file immagine',
        bing_source_error: 'Sorgente immagine Bing non disponibile',
        language_panel_title: '🌐 Lingua'
    },
    'tr': {
        extName: 'PlainTab · Minimal Başlangıç Sayfası',
        search_placeholder: 'Web’de ara…',
        search_engine_title: 'Motoru değiştirmek için tıkla | Aramak için Enter',
        lang_button_title: 'Dil değiştir',
        settings_icon_title: 'Duvar kağıdı ayarları',
        panel_title: '🖼️ Duvar kağıdı ayarları',
        wallpaper_bing: 'Geçerli: 🌄 Bing günlük',
        wallpaper_local: 'Geçerli: 📷 Yerel resim',
        upload_btn: '📁 Yerel duvar kağıdı seç',
        reset_btn: '🔄 Bing günlük olarak sıfırla',
        advanced_toggle: '⚙️ Gelişmiş',
        search_mode_label: 'Arama çubuğu modu',
        search_mode_hover: 'Üzerine gelince',
        search_mode_always: 'Her zaman',
        search_mode_never: 'Asla',
        icon_opacity_label: 'Simge opaklığı',
        search_engine_label: 'Arama motoru',
        reset_advanced_btn: '🔄 Gelişmiş ayarları sıfırla',
        local_upload_error: 'Duvar kağıdı kaydedilemedi: ',
        file_type_error: 'Lütfen bir resim dosyası seçin',
        bing_source_error: 'Bing resim kaynağı kullanılamıyor',
        language_panel_title: '🌐 Dil'
    },
    'pl': {
        extName: 'PlainTab · Minimalistyczna strona startowa',
        search_placeholder: 'Szukaj w internecie…',
        search_engine_title: 'Kliknij, aby zmienić silnik | Enter, aby szukać',
        lang_button_title: 'Zmień język',
        settings_icon_title: 'Ustawienia tapety',
        panel_title: '🖼️ Ustawienia tapety',
        wallpaper_bing: 'Bieżąca: 🌄 Bing dnia',
        wallpaper_local: 'Bieżąca: 📷 Obraz lokalny',
        upload_btn: '📁 Wybierz lokalną tapetę',
        reset_btn: '🔄 Przywróć Bing dnia',
        advanced_toggle: '⚙️ Zaawansowane',
        search_mode_label: 'Tryb paska wyszukiwania',
        search_mode_hover: 'Po najechaniu',
        search_mode_always: 'Zawsze',
        search_mode_never: 'Nigdy',
        icon_opacity_label: 'Przezroczystość ikony',
        search_engine_label: 'Silnik wyszukiwania',
        reset_advanced_btn: '🔄 Przywróć zaawansowane ustawienia',
        local_upload_error: 'Nie udało się zapisać tapety: ',
        file_type_error: 'Wybierz plik obrazu',
        bing_source_error: 'Źródło obrazów Bing niedostępne',
        language_panel_title: '🌐 Język'
    },
    'vi': {
        extName: 'PlainTab · Trang bắt đầu tối giản',
        search_placeholder: 'Tìm kiếm trên Web…',
        search_engine_title: 'Nhấp để đổi công cụ | Enter để tìm',
        lang_button_title: 'Đổi ngôn ngữ',
        settings_icon_title: 'Cài đặt hình nền',
        panel_title: '🖼️ Cài đặt hình nền',
        wallpaper_bing: 'Hiện tại: 🌄 Bing hàng ngày',
        wallpaper_local: 'Hiện tại: 📷 Ảnh cục bộ',
        upload_btn: '📁 Chọn hình nền cục bộ',
        reset_btn: '🔄 Đặt lại về Bing hàng ngày',
        advanced_toggle: '⚙️ Nâng cao',
        search_mode_label: 'Chế độ thanh tìm kiếm',
        search_mode_hover: 'Khi di chuột',
        search_mode_always: 'Luôn hiện',
        search_mode_never: 'Ẩn',
        icon_opacity_label: 'Độ mờ biểu tượng',
        search_engine_label: 'Công cụ tìm kiếm',
        reset_advanced_btn: '🔄 Đặt lại cài đặt nâng cao',
        local_upload_error: 'Lưu hình nền thất bại: ',
        file_type_error: 'Vui lòng chọn tệp hình ảnh',
        bing_source_error: 'Nguồn ảnh Bing không khả dụng',
        language_panel_title: '🌐 Ngôn ngữ'
    }
};

// 语言列表（面板展示顺序）
window.LanguageList = [
    { code: 'zh-CN', name: '中文 (简体)' },
    { code: 'zh-TW', name: '中文 (繁體)' },
    { code: 'en', name: 'English' },
    { code: 'es', name: 'Español' },
    { code: 'hi', name: 'हिन्दी' },
    { code: 'ar', name: 'العربية' },
    { code: 'pt', name: 'Português' },
    { code: 'ru', name: 'Русский' },
    { code: 'ja', name: '日本語' },
    { code: 'de', name: 'Deutsch' },
    { code: 'ko', name: '한국어' },
    { code: 'fr', name: 'Français' },
    { code: 'it', name: 'Italiano' },
    { code: 'tr', name: 'Türkçe' },
    { code: 'pl', name: 'Polski' },
    { code: 'vi', name: 'Tiếng Việt' }
];